### PR TITLE
[FEATURE] add possibility to overwrite description of core fields

### PR DESCRIPTION
**Pull request by can0199**
Hello,
 I had a use case where I wanted to overwrite not only the label but also the description of a core field, this was not possible with the current version of the mask, so I implemented it myself. 
I would be happy if this is also possible in the official version therefore I created the pull request

### CODE REVIEW

**Comment by nhovratov** [comment]
Cool, thank you for your contribution! Do you want to take care of the tests?

**Comment by can0199** [comment]
> Cool, thank you for your contribution! Do you want to take care of the tests?

yes , i can try

**Comment by nhovratov** [comment]
Looks like overriding descriptions is a v11 only feature. I was wondering, why it doesn't work :)

Some remarks from my side:
- Let's not limit it by core fields. This works just as fine with mask fields as well.
- Maybe we shouldn't generate the tsconfig in TYPO3 v10. It does no harm, but I think is clearer to only add it in v11.
- Make the description field a textarea. This way we can add newlines.

**Comment by can0199** [comment]
i tested it only with typo3 11 but good to know, then i inject the tsconfig only when typo3 11 is used. Also I will convert the field to a textarea and inject it for the other mask fields too. 

With the unittests I have some problems with WSL2 and ddev as my development environment tool, there I need some time .

Glad you like my idea

**Comment by nhovratov** [comment]
The other fields already have the description field, I think it would be enough to remove the condition for core fields in the TypoScriptCodeGenerator.

I'm on WSL2/ddev, too. If you need help setting up the tests, hit me up.
It should be simply `ddev composer install` inside mask and to run the tests `Build/Scripts/runTests.sh`.

**Comment by can0199** [comment]
> The other fields already have the description field, I think it would be enough to remove the condition for core fields in the TypoScriptCodeGenerator.
> 
> I'm on WSL2/ddev, too. If you need help setting up the tests, hit me up. It should be simply `ddev composer install` inside mask and to run the tests `Build/Scripts/runTests.sh`.

I do your steps but i got the following error from the runTest script

> Could not open input file: vendor/phpunit/phpunit/phpunit

I also added the version check typo3 > 10 and also removed the core field condition, so now other maks fields can be overridden.

At the moment I try to allow multiple lines for the description, unfortunately it does not work at the moment because the \n are not converted to br tags I think there is a bug in the core. I'm taking a closer look at it right now.

**Comment by nhovratov** [comment]
> I do your steps but i got the following error from the runTest script
> 
> > Could not open input file: vendor/phpunit/phpunit/phpunit

Oh, I think you have to run composer install not inside ddev container.
Can you try it again? Else, I will make the tests work, no problem.

> 
> I also added the version check typo3 > 10 and also removed the core field condition, so now other maks fields can be overridden.

Nice.

> 
> At the moment I try to allow multiple lines for the description, unfortunately it does not work at the moment because the \n are not converted to br tags I think there is a bug in the core. I'm taking a closer look at it right now.

Hm maybe it's because you can't add newlines in tsconfig?
But it should work theoretically:

typo3/sysext/backend/Classes/Form/FieldInformation/TcaDescription.php:41

            if (trim($fieldInformationText) !== '') {
                $resultArray['html'] = '<span class="formengine-field-item-description text-muted">' . nl2br(htmlspecialchars($fieldInformationText)) . '</span>';
            }

**Comment by can0199** [comment]
> Oh, I think you have to run composer install not inside ddev container.
> Can you try it again? Else, I will make the tests work, no problem.

you mean in my wsl2 distro?

> Hm maybe it's because you can't add newlines in tsconfig?
> But it should work theoretically:
> 
> typo3/sysext/backend/Classes/Form/FieldInformation/TcaDescription.php:41

yes because of this, i debugged the core and when i try to set this as descripiton "example \nnew line" i got with xdbeug following "example \\nnew line" then the nl2br can not convert it, i think  because of the duplicated backslash it goes wrong i try to identify where the second backslahs comes from.

Alos i try to make the overwriting from the description field work for typo3 10 with an eventlistener

**Comment by can0199** [comment]
now the unittest are working, i installed php and composer on the wsl2 distro and make composer install, thanks for youre help!

**Comment by nhovratov** [comment]
> you mean in my wsl2 distro?
yes

> yes because of this, i debugged the core and when i try to set this as descripiton "example \nnew line" i got with xdbeug following "example \nnew line" then the nl2br can not convert it, i think because of the duplicated backslash it goes wrong i try to identify where the second backslahs comes from.

Alright, tell me if you find something.

> Alos i try to make the overwriting from the description field work for typo3 10 with an eventlistener
Would be very cool, but let's make it work for v11 first.
I mean don't waste too much effort for v10, if it's easy, go for it.

**Comment by can0199** [comment]
> yes because of this, i debugged the core and when i try to set this as descripiton "example \nnew line" i got with xdbeug following "example \nnew line" then the nl2br can not convert it, i think because of the duplicated backslash it goes wrong i try to identify where the second backslahs comes from.
> 

> > Alright, tell me if you find something.

I think i found the problem, i think the parsing of the typoscript makes the problem in the file 
`typo3/sysext/core/Classes/TypoScript/Parser/TypoScriptParser.php`

on line 169 there is an explode function 
`  $this->raw = explode(LF, $string);`
LF is in my case "\n"
after the explode done then there ist \\n after this the nl2br cant convert it 
Screenshot_1

do you  have any idea to prevent this handling ?

**Comment by nhovratov** [comment]
> do you have any idea to prevent this handling ?

Yes, we need this multiline syntax of typoscript:

```
TCEFORM.tt_content.header.description (
	Test
  	wrap
)
```

**Comment by can0199** [comment]
thanks, i commit the changes now its working. now only the unittests has to be adjusted, i try it but i think is quit hard for me because i never used unit tests :D

**Comment by can0199** [comment]
now it works for typo3 10 too, i no longer inject the description via tsconfig but via the TCA using columnsOverride.
Unfortunately I haven't managed to fix the tests yet, if I can I would look for it again tomorrow

**Comment by nhovratov** [comment]
Perfect! Almost forgot about columsOverride.
You can try to fix the tests.
What I can see is:
- TableDefinitionCollection line 347
Because `descriptions` is new and might be missing in the json data, we need a check here.
For example `return $element->descriptions[$fieldIndex] ?? '';`

- A lot of places, which now have a descriptions array in the result. This needs to be added to the expected array result.
Just run the tests and they will show you the exact test case. You can fix them one by one until all tests are green.

**Comment by can0199** [comment]
thanks for your help, if i can i look this evening into that

**Comment by can0199** [comment]
> Perfect! Almost forgot about columsOverride. You can try to fix the tests. What I can see is:
> 
> * TableDefinitionCollection line 347
>   Because `descriptions` is new and might be missing in the json data, we need a check here.
>   For example `return $element->descriptions[$fieldIndex] ?? '';`
> * A lot of places, which now have a descriptions array in the result. This needs to be added to the expected array result.
>   Just run the tests and they will show you the exact test case. You can fix them one by one until all tests are green.

i fixed all unittests and also found several bugs which i also fixed. I think now ist working great

**Comment by nhovratov** [comment]
Hey, thanks for taking care!
Yes, the Palette descriptions are new in v11. They were in my backlog to implement.
The only failing tests are now the deprecated ones. The test cases need simply to be copied over.

Will take care.

**Comment by can0199** [comment]
> Hey, thanks for taking care!
> Yes, the Palette descriptions are new in v11. They were in my backlog to implement.
> The only failing tests are now the deprecated ones. The test cases need simply to be copied over.
> 
> Will take care.

Hey, 
thanks for fixing the deprecated tests, if i can do something else for this functionality let me know

**Comment by nhovratov** [comment]
> Hey, thanks for fixing the deprecated tests, if i can do something else for this functionality let me know

Leave the rest to me. Will fix the last failing test and review everything thouroughly.
Great job! Nice to have some help now and then :)
You will be mentioned in the v7.1 release.

**Comment by nhovratov** [comment]
It's in!

I've extracted the TCA generation into an own method and added some tests.
Also added backwards compatibility for old description configuration.

Once again, thank you very much for your effort. Very appreciated.

**Comment by can0199** [comment]
> It's in!
> 
> I've extracted the TCA generation into an own method and added some tests.
> Also added backwards compatibility for old description configuration.
> 
> Once again, thank you very much for your effort. Very appreciated.

nice, youre welcome im glad you like it. i have also an other idea i have is to allow overwriting the validation options for core fields if you think its a good feature i can look into it in the next weeks

**Comment by nhovratov** [comment]
> nice, youre welcome im glad you like it. i have also an other idea i have is to allow overwriting the validation options for core fields if you think its a good feature i can look into it in the next weeks

Sounds interesting. Can sometimes come in handy to be able to override evals of core fields on a per element level.
Most importantly the required option. I'm totally in for that, but would target it for the release after 7.1.
I want to resolve some last todos UI/UX-wise and bugfixes and finally prepare the next release.
Are you on TYPO3 slack? We could coordinate next goals there.

**Comment by can0199** [comment]
> > nice, youre welcome im glad you like it. i have also an other idea i have is to allow overwriting the validation options for core fields if you think its a good feature i can look into it in the next weeks
> 
> Sounds interesting. Can sometimes come in handy to be able to override evals of core fields on a per element level.
> Most importantly the required option. I'm totally in for that, but would target it for the release after 7.1.
> I want to resolve some last todos UI/UX-wise and bugfixes and finally prepare the next release.
> Are you on TYPO3 slack? We could coordinate next goals there.

ahh okay, i found my slack account now :D and yes im on the Typo3 slack my slack name is can0199

**Pull request merged**
