### PR TITLE
[TASK] fix php 8 warning which is thrown in BackendLayoutRepository

### PR DESCRIPTION
**Pull request by can0199**
with php8 typo3 throws an error if $requestPage value is of type bool 

```
PHP Warning: Trying to access array offset on value of type bool in /mask/Classes/Domain/Repository/BackendLayoutRepository/BackendLayoutRepository.php line 32
```

### CODE REVIEW

**Comment by nhovratov** [comment]
Looks good, can you give me an example, how to reproduce it?

**Comment by can0199** [comment]
i think i had this error because the backend_layout field of the page was empty

**Comment by nhovratov** [comment]
Can it be, that you tried to open a page, which is disabled? This way I can reproduce it. The querybuilder won't of course appear in the result because of the default restrictions.

I don't think it is possible to receive `false` otherwise, because if you open a page, you will always have this existing page.

Then the bugfix would be, to remove the hidden restriction instead of skipping the backend layout retrieval.

**Comment by can0199** [comment]
tomorrow i will try to reproduce the error

**Comment by nhovratov** [comment]
Can you check then, if this fixes it?
https://github.com/Gernott/mask/commit/e9268dab1d629c753869e2799cc03abe15da6717

**Comment by can0199** [comment]
I tried to reproduce the error and I think you are right that it only occurs when the page is disabled, your patch works smoothly

**Comment by can0199** [comment]
this issue was fixed with commit https://github.com/Gernott/mask/commit/e9268dab1d629c753869e2799cc03abe15da6717

**Pull request closed without merging**
