### PR TITLE
Feature/editorconfig

### PR DESCRIPTION
**Pull request by Julian-B90**
- add [.editorconfig](http://editorconfig.org/)
- replace tab with space´s

### CODE REVIEW

**Comment by markuspoerschke** [comment]
The usage of *php-cs-fixer* cannot replace the *.editorconfig*. 

@Gernott To me this PR looks like it can be merged.

**Comment by IchHabRecht** [comment]
> The usage of php-cs-fixer cannot replace the .editorconfig.

Not sure where you have read this but that was not what I tried to say.

**Comment by markuspoerschke** [comment]
@IchHabRecht I wanted to underline that this PR can be merged. There is no need to wait for the php-cs-fixer configuration in this PR.

**Comment by IchHabRecht** [comment]
@markuspoerschke Have you read my comment about using the same style as the core and most other extensions use?

**Comment by markuspoerschke** [comment]
@IchHabRecht I thought that this was fixed in https://github.com/Gernott/mask/pull/57/commits/acd78b9fa75bed6835ae40a27d674730b42b4123 already... 

But after comparing it again I saw that there are minor changes to the file existing in core. Mabye it was copied 2 month ago from a different version that `8.7`... :(

**Comment by butu** [comment]
Thank you for your input. I added a .editorconfig! :)

**Pull request closed without merging**
