### PR TITLE
Prevent warning if array is null

### PR DESCRIPTION
**Pull request by Weissheiten**
fix via null coalescing operator

### CODE REVIEW

**Comment by Gernott** [comment]
Why is this necessary in this case? $messages is initalized as array in checkFolders().

**Comment by Weissheiten** [comment]
The suggestion was a reaction to a warning on my dev stack with PHP 7.2 and activated warnings. (I did not debug the variable at runtime on this dev stack, the problem seemed to be related with the other pull request)
If there are other means to fix this please deny the request and proceed accordingly.

**Comment by Gernott** [comment]
Can you please test with the migrated PR 135 again and check if the warning still appears?

**Comment by Weissheiten** [comment]
#1476107295: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /app/Web/typo3conf/ext/mask/Classes/Helper/FieldHelper.php line 96 (More information)

Mask 3.1.0, TYPO3 8.7.12, PHP 7.2.1 - warnings active

**Comment by butu** [comment]
This should be fixed with the latest commits.

**Pull request closed without merging**
