### PR TITLE
Check code style

### PR DESCRIPTION
**Pull request by markuspoerschke**
This pull request adds PHP CS Fixer configuration and a Travis CI configuration that checks the code style. After merge the fixer needs to be executed once to initially fix the code style. Maybe there are some manual changes needed (e.g. for the file php comment and copyright notice).

**There are some points that might need some change:**
* As a ruleset I just picket the PSR2 and ordered_imports. Maybe some more rules have to be applied to match the [*TYPO3 CMS Coding Guidelines*](https://docs.typo3.org/typo3cms/CodingGuidelinesReference/). For now I would leave it as it is in this PR.
* I found different file headers and copyright notices. I just copied the default from [the TYPO3 documentation](https://docs.typo3.org/typo3cms/CodingGuidelinesReference/PhpFileFormatting/FileStructure/Index.html#copyright-notice).

**Tasks needs to be done after merge:**
* Initially run `php-cs-fixer fix` to cleanup old files.
* Connect Travis CI

### CODE REVIEW

**Comment by markuspoerschke** [comment]
@IchHabRecht I just found that you did this already for the *mask_export* extension. Do you think it makes sense to copy the `.php_cs` from there?

**Comment by IchHabRecht** [comment]
I use php-cs-fixer only during development. For style check I use StyleCi which I can integrate in a better way into GitHub repositories. I don't need to wait for travis to get some style information and they are really fast within some seconds. Furthermore with introducing a style check, you need to change the code to match the style, of course. This commit is completely missing here.

**Comment by IchHabRecht** [comment]
The rules from mask_export's php_cs.dist are very strict. Not sure if the development team of mask will use those strict rules for their development.

**Comment by markuspoerschke** [comment]
> Furthermore with introducing a style check, you need to change the code to match the style, of course. This commit is completely missing here.

In my expirience this will cause very early a merge conflict. I think it is easier if this will be done directly on master. Because after any other pull request is merged there will be a conflict in this one. I would like to avoid this.

> The rules from mask_export's php_cs.dist are very strict. Not sure if the development team of mask will use those strict rules for their development.

Thanks for you input. Let’s wait for the maintainers what they think about this. :)

**Comment by markuspoerschke** [comment]
@Gernott Can you check this? A consistent Style Guide will avoid a lots of merge conflicts in the future and makes it easier to contribute to this project.

After merging the PHP CS Fixer has to be executed once manually to fix the current code.

**Comment by Gernott** [comment]
Done by @nhovratov in Branch v6.x.x

**Pull request closed without merging**
