### PR TITLE
[TASK] Use symfony dependency injection

### PR DESCRIPTION
**Pull request by nhovratov**
All classes dependencies are moved to the constructor and use
the new symfony DI. Usages of ObjectManager are removed.
Removed @Inject annotations.

Other notable changes:
- Due to a circular dependency of FieldHelper and
StorageRepository the method "getFormType" has been extracted
to StorageRepository
- TypoScript static template moved to tca overrides sys_template.php

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi,

Just wanted to clarify that this is a breaking change and would needed to have a new major release.

**Comment by nhovratov** [comment]
You mean moving the method to another class?

**Comment by IchHabRecht** [comment]
Mo, I mean changing the constructor arguments for example.

**Comment by nhovratov** [comment]
Yes, technically it's breaking, but it should be fine. Most constructor arguments were optional anyway.

**Comment by IchHabRecht** [comment]
It's not fine for the mask_export extension that uses and depends on the mask classes ;-)

**Comment by nhovratov** [comment]
Oh, i see. Will revert it then in the next patch and release it in mask v6.

**Comment by IchHabRecht** [comment]
I'm currently trying to find a suitable workaround. Never mind, but I would kindly ask you to have the export some more in yours heads. Thanks for taking care.

**Comment by nhovratov** [comment]
Yes, i wasn't really aware of that, sorry. So you think it's better to revert it or for you to find a workarond?

**Comment by IchHabRecht** [comment]
To get it working right now, I need to find a workaround.

**Comment by nhovratov** [comment]
For now you can use the previous version to get it working. I will ask Gernot to release a new version with the revert as soon as possible.

**Pull request merged**
