### PR TITLE
[TASK] get icon with PathUtility instead of ResourceFactory

### LINKED ISSUE #652: Preview-Icons are stored in the sys_file table
We defined PreviewIcons as SVG for our mask elements. These icons are stored in the table sys_file.
Usually the should just be loaded from the file system, without any entry in the sys_file table.

By taking a look into the PreviewIconResolver.php I found out that the problem is caused by the function:
 `$this->resourceFactory->retrieveFileOrFolderObject`

There probably is some logic behind the function which automatically creates an entry in the sys_file table.

I suggest to use the function `PathUtility::getPublicResourceWebPath` instead

Tested on:
TYPO3 12.4.22
PHP 8.3

### PR DESCRIPTION
**Pull request by jakowidhalm**
Closes #652

### CODE REVIEW

**Comment by nhovratov** [comment]
@jakowidhalm Thank you very much for the PR!

**Comment by TheOnlyMarkus** [comment]
Unfortunately, this PR prevents storing content element preview Icons outside typo3conf/ext/ for example in fileadmin/mask-icons/. The error causes the mask backend module load blank and also breaks the "page" module when clicking a page on page tree. Downgrading mask to 8.3.11 makes everything work again and preview Icons are displayed too.

Stacktrace:
```php
Array
(
    [mode] => WEB
    [application_mode] => BE
    [exception_class] => TYPO3\CMS\Core\Resource\Exception\InvalidFileException
    [exception_code] => 1630089406
    [file] => /www/typo3shared/typo3_src-12.4.14/typo3/sysext/core/Classes/Utility/PathUtility.php
    [line] => 100
    [message] => Resource paths must start with "EXT:"
    [request_url] => https://www.example.org/typo3/ajax/mask/elements?token=--AnonymizedToken--
    [exception] => TYPO3\CMS\Core\Resource\Exception\InvalidFileException: Resource paths must start with "EXT:" in /www/typo3shared/typo3_src-12.4.14/typo3/sysext/core/Classes/Utility/PathUtility.php:100
Stack trace:
#0 /www/website/html/typo3conf/ext/mask/Classes/Imaging/PreviewIconResolver.php(58): TYPO3\CMS\Core\Utility\PathUtility::getPublicResourceWebPath()
#1 /www/website/html/typo3conf/ext/mask/Classes/Imaging/PreviewIconResolver.php(41): MASK\Mask\Imaging\PreviewIconResolver->getPreviewIconPath()
#2 /www/website/html/typo3conf/ext/mask/Classes/Imaging/IconProvider/ContentElementIconProvider.php(48): MASK\Mask\Imaging\PreviewIconResolver->isPreviewIconAvailable()
#3 /www/website/html/typo3conf/ext/mask/Classes/Imaging/IconProvider/ContentElementIconProvider.php(39): MASK\Mask\Imaging\IconProvider\ContentElementIconProvider->generateMarkup()
#4 /www/typo3shared/typo3_src-12.4.14/typo3/sysext/core/Classes/Imaging/IconFactory.php(108): MASK\Mask\Imaging\IconProvider\ContentElementIconProvider->prepareIconMarkup()
#5 /www/website/html/typo3conf/ext/mask/Classes/Controller/AjaxController.php(389): TYPO3\CMS\Core\Imaging\IconFactory->getIcon()
#6 /www/typo3shared/typo3_src-12.4.14/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(77): MASK\Mask\Controller\AjaxController->elements()
[...]
```

**Comment by nhovratov** [comment]
@TheOnlyMarkus All Mask resources must be inside an extension since a long time ago. The fact that it worked before was more of a bug than a feature. Please migrate your icons to a Resources/Public folder inside your extension.

This is the case since Mask v8: https://docs.typo3.org/p/mask/mask/9.0/en-us/ChangeLog/8.0/Index.html#breaking-changes

**Comment by TheOnlyMarkus** [comment]
Sorry, but this is unfeasonable. Most people aren't programmers and don't know how to create a extension. Please revert this PR. It worked for a very long time until November 2024.

**Comment by nhovratov** [comment]
You don't need to be a programmer to create an extension. This is basic integrator knowledge.

**Comment by TheOnlyMarkus** [comment]
Sorry, you are wrong. But I understand you won't make that change and that's a shame because upgrading to next major version is now a hassle which proves once again that its not worth reporting errors to open source projects but instead just move on.

**Comment by nhovratov** [comment]
I don't like the tone at all. Disliking every comment won't help you. If you are not able to discuss technical topics in an appropriate manner, then this is a you problem. The fact that you are able to use this extesion in TYPO3 v12/v13 for free(!) is thanks to my time and passion that went into the development. Mask has one of the smoothest upgrade paths thanks to dozens of backwards compatibility code paths. Simply refusing to move some files somewhere else and calling it a "hassle" is preposterous.

**Comment by butu** [comment]
Why so disrespectful? @nhovratov pointed you to the documentation where this change is listed and helped you find the error. You just have to move the Icons into an Extension. How is this a hassle?

**Comment by TheOnlyMarkus** [comment]
And only for the record, my company did invest in mask in the past.

**Comment by nhovratov** [comment]
wtf

**Pull request merged**
